const QUOTES: string[] = [
  "The secret of getting ahead is getting started.",
  "It does not matter how slowly you go, as long as you do not stop.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "The only way to do great work is to love what you do.",
  "Either you run the day or the day runs you.",
  "Action is the foundational key to all success.",
  "Small daily improvements are the key to staggering long-term results.",
  "Discipline is the bridge between goals and accomplishment.",
  "You don't have to be great to start, but you have to start to be great.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Do something today that your future self will thank you for.",
  "Motivation gets you going. Discipline keeps you growing.",
  "The pain of discipline is far less than the pain of regret.",
  "Every day is a new opportunity to improve yourself.",
  "Push yourself because no one else is going to do it for you.",
  "Don't watch the clock; do what it does. Keep going.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The key to success is to focus on goals, not obstacles.",
  "Little by little, a little becomes a lot.",
  "You are one decision away from a totally different life.",
  "Stay focused and never give up.",
  "Nothing will work unless you do.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Start where you are. Use what you have. Do what you can.",
  "Champions keep playing until they get it right.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "If you do what you always did, you will get what you always got.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Just when the caterpillar thought the world was ending, it became a butterfly.",
  "Successful entrepreneurs are givers and not takers of positive energy.",
  "Whenever you see a successful person, you only see the public glories.",
  "The ones who are crazy enough to think they can change the world, are the ones that do.",
  "Don't raise your voice. Improve your argument.",
  "Hard work beats talent when talent doesn't work hard.",
  "There are two types of people who will tell you that you cannot make a difference: those who are afraid to try, and those who are afraid you will succeed.",
  "Don't be afraid to give up the good to go for the great.",
  "No masterpiece was ever created by a lazy artist.",
  "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.",
  "If you can't yet do great things, do small things in a great way.",
  "You can't use up creativity. The more you use, the more you have.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "The secret to getting ahead is getting started.",
  "You miss 100% of the shots you don't take.",
];

/**
 * Returns a deterministic quote for a given day number.
 */
export function getQuoteForDay(dayNumber: number): string {
  return QUOTES[(dayNumber - 1) % QUOTES.length];
}
